---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ldc1

resources:
  - 00-mcp-ran-cu-ldc1-dell00.yaml
  - 00-mcp-ran-du-ldc1-dell01.yaml
  - 01-pao-ran-cu-ldc1-dell00-profile0.yaml
  - 01-pao-ran-du-ldc1-dell01-profile0.yaml
  #- 02-node-labels.yaml
  #- 03-node-labels.yaml
