---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ldc1

resources:
  # SRIOV Configs
  #- 00-ldc1-sriov-namespace.yaml
  - 00-ldc1-sriov-node-policy.yaml
  - 01-ldc1-sriov-vran-mgmt.yaml
  - 01-ldc1-sriov-vran-mh.yaml
    #  - 01-ldc1-sriov-vran-ar.yaml
  - 01-ldc1-sriov-vran-fh.yaml
  - 01-ldc1-sriov-vran-mp.yaml
  # Storage Configs
  # - 02-ldc1-local-storage-dell03.yaml
  # PTP Configs
  #- 03-ldc1-ptp-smci02.yaml
  - 03-ldc1-ptp-smci02-e810.yaml
  # ACC100
  - 04-sriovfecclusterconfig-ran-du-ldc1-smci02.yaml
