# gnb-fiesta-cars2-lab-bmc-secret & assisted-deployment-pull-secret need to be created under same namespace fiesta
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "du1-1-fiesta-cars2-lab"
  namespace: "du1-1-fiesta-cars2-lab"
spec:
  baseDomain: "cars2.lab"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.18.23-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd7Jj5iFCWv9IHJK9H+2O3lyPs36moAxeAUiHvzRS3uzqGxxB33BnTRBNDKsoDFSGJX0J4bd5b+XyCPdhFOfvn/xhmAcm6d8GALS+139e8d+No8h2QgZy0OVJFp844k4nmz4wew5/+X9DN40ZURYerekbVc58hw1+rTu0uM2jQ0cE2QmEf3qGKHx9UJW8t6IsMzwnrikBH30sYqn2NcBE+/c8JzlLc3PvvenlY0iQkpukI1A5E9GGMR9OS/q+w6FH85zvSgUatOV7Q5lg45QUF+V77DrfX5+niI+NK1g70pRvD8481SAdXrHPB5vK4vQEmJ4pz83IKYHVuPzRnjzYKv1jV33oReyyMqyk44Rsfkxl4i5SJ9z7q/EVmTjvurzD6ofi3Dg0+PL18eTcjuPFdCxSCUFsnr5N9CRHCxHRQpxoZTD7sYD4jDGNygawLvhxcvgKGBZzP53NRCzRFOMFmZsLPLQRaNOsgKRPAohmrn5l8+1xG5ltVauOwAFlKUxk="
  clusters:
  - clusterName: "fiesta"
    networkType: "OVNKubernetes"
     # installConfigOverrides is a generic way of passing install-config
     # parameters through the siteConfig.  The 'capabilities' field configures
     # the composable openshift feature.  In this 'capabilities' setting, we
     # remove all but the marketplace component from the optional set of
     # components.
     # Notes:
    # - NodeTuning is needed for 4.13 and later, not for 4.12 and earlier
    installConfigOverrides: "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"marketplace\", \"OperatorLifecycleManager\", \"NodeTuning\", \"Ingress\" ] }}"
    # It is strongly recommended to include crun manifests as part of the additional install-time manifests for 4.13+.
    # The crun manifests can be obtained from source-crs/optional-extra-manifest/ and added to the git repo ie.sno-extra-manifest.
    # extraManifestPath: sno-extra-manifest
    clusterLabels:
      common-du-418: true
      group-smcx12-vse2: ""
      #sites: "fiesta-cars2-lab"
      #vseloki: true
      #vseextras: true
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      - cidr: fd01::/48
        hostPrefix: 64
    machineNetwork:
      - cidr: 192.168.38.128/26
      - cidr: 2600:52:7:300::0/64
    serviceNetwork:
      - 172.30.0.0/16
      - fd02::/112
    additionalNTPSources:
      - clock.cars2.lab
      - clock-v6.cars2.lab
    # Initiates the cluster for workload partitioning. Setting specific reserved/isolated CPUSets is done via PolicyTemplate
    # please see Workload Partitioning Feature for a complete guide.
    cpuPartitioningMode: AllNodes
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "du1-1.fiesta.cars2.lab"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "redfish-virtualmedia://192.168.38.199/redfish/v1/Systems/1/"
        bmcCredentialsName:
          name: "gnb-fiesta-cars2-lab-bmc-secret"
        bootMACAddress: "3c:ec:ef:b6:ce:12"
        # Use UEFISecureBoot to enable secure boot
        bootMode: "UEFI"
        rootDeviceHints:
          wwn: "0x500a075138277708"
        nodeNetwork:
          interfaces:
            - name: eno1
              macAddress: "3c:ec:ef:b6:ce:10"
            - name: eno2
              macAddress: "3c:ec:ef:b6:ce:11"
            - name: eno3
              macAddress: "3c:ec:ef:b6:ce:12"
            - name: ens6f0
              macAddress: "50:7c:6f:30:fc:7c"
            - name: ens6f1
              macAddress: "50:7c:6f:30:fc:7d"
            - name: ens6f2
              macAddress: "50:7c:6f:30:fc:7e"
            - name: ens6f3
              macAddress: "50:7c:6f:30:fc:7f"
          config:
            interfaces:
            - name: eno1
              type: ethernet
              state: down
            - name: eno2
              type: ethernet
              state: down
            - name: eno3
              type: ethernet
              state: up
              ipv4:
                enabled: true
                address:
                  - ip: "192.168.38.144"
                    prefix-length: 26
                dhcp: false
              ipv6:
                enabled: true
                address:
                  - ip: "2600:52:7:300::144"
                    prefix-length: 64
                autoconf: false
                dhcp: false
            - name: ens6f0
              type: ethernet
              state: down
            - name: ens6f1
              type: ethernet
              state: down
            - name: ens6f2
              type: ethernet
              state: down
            - name: ens6f3
              type: ethernet
              state: down
            dns-resolver:
              config:
                server:
                  - 192.168.38.12
                  - 2600:52:7:38::12
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.38.129
                next-hop-interface: eno3
              - destination: ::/0
                next-hop-address: 2600:52:7:300::1
                next-hop-interface: eno3
