---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: fec3

resources:
  # SRIOV Configs
  # review ns
  #- 00-fec3-sriov-namespace.yaml
  - 00-fec3-sriov-node-policy.yaml
  # ran related sriov nics, consider delete or use for ueransim
  - 01-fec3-sriov-vran-mgmt.yaml
  - 01-fec3-sriov-vran-mh.yaml
  - 01-fec3-sriov-vran-fh.yaml
  - 01-fec3-sriov-vran-ar.yaml
  - 01-fec3-sriov-vran-mp.yaml
  # core sr-iov, using ens4f1 consider ens4f0
  - 01-fec3-sriov-bh-n2.yaml
  - 01-fec3-sriov-bh-n3.yaml
  - 01-fec3-sriov-bh-s1u.yaml
  - 01-fec3-sriov-bh-s1c.yaml
  - 01-fec3-sriov-wan-n6.yaml
  # Storage Configs
  # - 02-fec3-local-storage-dell03.yaml
  # PTP Configs
  - 03-fec3-ptp-dell03.yaml
  # N3k Configs
  # - 04-n3k.yaml
  # ACC100
  #- 04-sriovfecclusterconfig-ran-du-fec3-dell03.yaml
