---
apiVersion: v1
kind: ConfigMap
metadata:
  name: assisted-service-config
  namespace: open-cluster-management
data:
  LOG_LEVEL: "debug"
  SUPPORT_L2: "false"
  DISABLED_HOST_VALIDATIONS: "belongs-to-machine-cidr,belongs-to-majority-group"
  PUBLIC_CONTAINER_REGISTRIES: "quay.io,registry.svc.ci.openshift.org,registry.redhat.io"
  ISO_IMAGE_TYPE: "full-iso"
---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  annotations:
    unsupported.agent-install.openshift.io/assisted-service-configmap: 'assisted-service-config'
spec:
  databaseStorage:
    #bug, leave default class for now
    #storageClassName: lso-blockclass
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 90Gi
  filesystemStorage:
    #bug, leave default class for now
    #storageClassName: lso-filesystemclass
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 90Gi
  mirrorRegistryRef:
    # for disconnected installs
    name: "disconnected-mirror-config"
  osImages:
    #- openshiftVersion: "4.6"
    #  version: "46.82.202012051820-0"
    #  url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso"
    #  rootFSUrl: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-live-rootfs.x86_64.img"
    - openshiftVersion: "4.8"
      cpuArchitecture: x86_64
      version: "48.84.202107202156-0"
      url: "http://10.40.0.100/ztp-dave/rhcos-4.8.14-x86_64-live.x86_64.iso"
      rootFSUrl: "http://10.40.0.100/ztp-dave/rhcos-4.8.14-x86_64-live-rootfs.x86_64.img"
    - openshiftVersion: "4.9"
      cpuArchitecture: x86_64
      version: "49.84.202110081407-0"
      url: "http://10.40.0.100/ztp-dave/rhcos-4.9.0-x86_64-live.x86_64.iso"
      rootFSUrl: "http://10.40.0.100/ztp-dave/rhcos-4.9.0-x86_64-live-rootfs.x86_64.img"
    - openshiftVersion: "4.10"
      cpuArchitecture: x86_64
      version: "410.84.202201251210-0"
      url: "http://10.40.0.100/ztp-dave/rhcos-4.10.3-x86_64-live.x86_64.iso"
      rootFSUrl: "http://10.40.0.100/ztp-dave/rhcos-4.10.3-x86_64-live-rootfs.x86_64.img"
